syntax = "proto3";

package sports.event.v1;

option go_package = "github.com/university/sports-event-planner-platform/services/event-service/proto/event/v1;eventv1";

service EventService {
  rpc CreateEvent(CreateEventRequest) returns (EventResponse);
  rpc GetEvent(GetEventRequest) returns (EventResponse);
  rpc ListEvents(ListEventsRequest) returns (ListEventsResponse);
  rpc UpdateEvent(UpdateEventRequest) returns (EventResponse);
  rpc DeleteEvent(DeleteEventRequest) returns (DeleteEventResponse);
  rpc JoinEvent(EventMembershipRequest) returns (EventResponse);
  rpc LeaveEvent(EventMembershipRequest) returns (EventResponse);
}

message Event {
  string id = 1;
  string sport = 2;
  string category = 3;
  string competition = 4;
  string title = 5;
  string description = 6;
  string start_time = 7;
  string end_time = 8;
  string status = 9;
  string country = 10;
  string city = 11;
  string created_at = 12;
  string updated_at = 13;
  string creator_id = 14;
  string location = 15;
  int32 max_participants = 16;
  int32 participants_count = 17;
}

message CreateEventRequest {
  string sport = 1;
  string category = 2;
  string competition = 3;
  string title = 4;
  string description = 5;
  string start_time = 6;
  string end_time = 7;
  string status = 8;
  string country = 9;
  string city = 10;
  string creator_id = 11;
  int32 max_participants = 12;
  string location = 13;
}

message GetEventRequest {
  string event_id = 1;
}

message UpdateEventRequest {
  string id = 1;
  string title = 2;
  string sport = 3;
  string location = 4;
  string start_time = 5;
  string end_time = 6;
  int32 max_participants = 7;
  string user_id = 8;
  string category = 9;
  string competition = 10;
  string description = 11;
  string status = 12;
  string country = 13;
  string city = 14;
}

message ListEventsRequest {
  string sport = 1;
  string competition = 2;
  string start_time_from = 3;
  string start_time_to = 4;
  string country = 5;
  int32 page = 6;
  int32 page_size = 7;
  string category = 8;
  string status = 9;
  string city = 10;
}

message EventResponse {
  Event event = 1;
}

message ListEventsResponse {
  repeated Event events = 1;
}

message DeleteEventRequest {
  string event_id = 1;
  string user_id = 2;
}

message DeleteEventResponse {
  string event_id = 1;
  bool deleted = 2;
}

message EventMembershipRequest {
  string event_id = 1;
  string user_id = 2;
}
